### ISSUE TITLE
@type refers to bookformattype

### ISSUE THREAD

**Issue by kjartanm** [HadrienGardeur/comics-manifest#1]
Should it not rather refer to http://bib.schema.org/ComicStory? 

Or maybe http://bib.schema.org/Book with bookFormat set to http://schema.org/GraphicNovel?

**Comment by HadrienGardeur** [comment]
Based on my understanding of schema.org, it should refer to:
- http://bib.schema.org/ComicIssue for single issues (fairly common in both comics and manga, less common in Europe)
- http://schema.org/GraphicNovel for longer works or collected editions

**Comment by kjartanm** [comment]
Well, I'm no expert on schema.org, but it seems to me there is an important difference between ComicIssue and GraphicNovel in that the first derives from CreativeWork, PublicationIssue etc, and the other is just part of an enumeration of formattypes.

There is an parallel with audiobooks, where I interpret the logic as the following:

You can say that something is an AudioBook (as you do), which implies that it is a CreativeWork and a MediaObject. 

Or you can say that something is an Book (also CreativeWork) with AudiobookFormat as bookFormatType. AudiobookFormat is on par with GraphicNovel.

In my opinion it would be preferable if @type derives from CreativeWork.

But, by the way, why not let PortableWebApplication be its own type?

**Comment by HadrienGardeur** [comment]
Well to be perfectly clear, `type` here is strictly meant for creating a nicer looking RDF graph (and provide more accurate metadata) when you extract it from JSON-LD. It's not necessary for a Web Publication client at all.

Instead of being simply a "RDF resource", the publication becomes whatever we put in `type`.

I also agree that it's better if its value derives from CreativeWork, but being able to use a bookFormatType directly is a convenient shortcut. If it's too much of a problem in terms of semantics, we'll simply have to include two elements instead of one.

> But, by the way, why not let PortableWebApplication be its own type?

We're not describing a Web Application here but a Web Publication, which is somehow different. Ideally, we would have a specific type for each.

**Comment by kjartanm** [comment]
Yes, sorry, meant to say portable web publication, but have been reading so much up on PWA lately :)

**Comment by HadrienGardeur** [comment]
Well, we're facing a bit of a chicken and egg problem:
- it's still early days for Web Publications, while I'm exploring with prototypes and draft documents, at a W3C/IDPF level we're still at the point where use cases are being refined
- the schema.org team wants to have a more stable set of elements, and will mostly consider new elements through extensions (such as bib.schema.org)
- we might need a specific type to make Web Publications a reality...
- ... but at the same time it's very likely that to have an official type in a schema.org extension, we'll need traction on Web Publications

**Comment by kjartanm** [comment]
Yes, I can see that. In that regard I support the profiling effort you do here since focusing on specific areas could help to get traction. How about creating a profile for facsimiles? Typical use case museums and libraries. I could help get funding, and introducing it outside the most commercial markets would probably be less painful?
